---
title: "MSDS 6306 - Case Study 2"
author: "R People: Jonathan Flores, Melissa Luzardo, Randy Park"
date: "March 23rd, 2018"
output: 
  md_document:
    variant: markdown_github
---

## Prepare Data & Libraries and Factorize columns for analysis
``` {r echo=TRUE, comment=NA, results='asis'}

##
#  md_document:
#    variant: markdown_github
##

## Reading from CaseStudy2-data.xlsx. The Excel file is on local
library("readxl")
library("tidyr")
library("devtools")
library("ggplot2")
library("dplyr")
library("knitr")
library("caret")
library("scales")
library("purrr")
require(gridExtra)

case_data <- data.frame(read_excel("data/CaseStudy2-data.xlsx"))

factor_cols <- c("Attrition", "BusinessTravel", "Department", "Education", "EducationField", "EnvironmentSatisfaction", "Gender", "JobInvolvement", "JobLevel", "JobRole", "JobSatisfaction", "MaritalStatus", "OverTime")
case_data[factor_cols] <- lapply(case_data[factor_cols], factor)

## Prepare attrition data

attrition_data <- case_data[which(case_data$Attrition == 'Yes'), ]
```

## Univariate 1 - attrition by looking with salary
``` {r echo=TRUE, comment=NA, results='asis'}
uni_1_cols <- c("HourlyRate", "DailyRate", "MonthlyIncome", "MonthlyRate", "PercentSalaryHike")
attrition_data[uni_1_cols] %>%
 gather() %>%     
 ggplot(aes(x = value)) +                     
 facet_wrap(~ key, scales = "free") +  
 geom_histogram(fill = "darkgreen")
```

## Quick glance at attrition data by department
``` {r echo=TRUE, comment=NA, results='asis'}
att_by_dept_tbl <- case_data %>% select(Attrition, Department) %>% group_by(Department) %>% arrange(Department) %>% table()

knitr::kable(att_by_dept_tbl)
```

## Univariate 1 - attrition by department
``` {r echo=TRUE, comment=NA, results='asis'}
att_by_dept <- data.frame(att_by_dept_tbl)
ggplot(att_by_dept, aes(x = reorder(Department, -Freq), y=Freq, fill=Attrition)) + 
    geom_bar(stat = "identity") + 
    ggtitle('Attrition by Department') + 
    theme(plot.title = element_text(hjust = 0.5)) +
    xlab('Department') + 
    ylab('Attrition')
```

## Univariate 2 - attrition with Age and Years at Company
``` {r echo=TRUE, comment=NA, results='asis'}
featurePlot(x = case_data[, c('Age', 'YearsAtCompany')], y = case_data$Attrition, plot = "density", auto.key = list(columns = 2))
```

## Univariate 3 - attrition by job role
``` {r echo=TRUE, comment=NA, results='asis'}
ggplot(case_data, aes(x = JobRole, fill = Attrition)) +
  stat_count(width = 0.5) +
  xlab("Job Role") +
  ylab("Count") +
  labs(fill = "Attrition") +
  coord_flip()

ggplot(case_data, aes(x = JobRole)) + 
  geom_bar(aes(fill = Attrition), position = 'fill') + 
  scale_y_continuous(labels = percent_format()) +
  ylab("Percentage") +
  coord_flip()
```

## Univariate 4 - attrition by education field
``` {r echo=TRUE, comment=NA, results='asis'}
ggplot(case_data, aes(x = EducationField, ..count..)) +
  geom_bar(aes(fill = Attrition), position="fill") +
  theme(axis.text.x = element_text(size  = 10, angle = 45,hjust = 1,vjust = 1))
```


## Summary
``` {r echo=TRUE, comment=NA, results='asis'}

## Summary section
```