---
title: "CS2"
author: "Melissa Luzardo"
date: "April 2, 2018"
output: 
  html_document:
   keep_md: true
---

## Source Documents

``` {r echo=TRUE, comment=NA, results='asis'}

#load requeried library

library("readxl")

#load file

case_data <- data.frame(read_excel("C:\\Users\\melis\\OneDrive\\Desktop\\SMU\\MSDS 6306 - Data Science\\Case Study 2\\CaseStudy2-data.xlsx"))

#Remove redundandt info
df <- case_data[,-c(9,10,22,27)]
```

Find correlation between parameters and Attrition

``` {r echo=TRUE, comment=NA, results='asis'}

# Convert characters to factors. First load required libraries; then code.
library(purrr)
library(dplyr)
df %>% map_if(is.character, as.factor) %>% as_data_frame -> df

#Adjust factor levels
levels(df$BusinessTravel)<-c("Non-Travel","Travel_Rarely","Travel_Frequently")

#make all variable numeric
numdf<-data.frame(sapply(df,as.numeric))

#Correlate variables
Attcor<-data.frame(cor(numdf))

#Create Attrition object
Attrition<- data.frame(Attcor$Attrition)

#Name attrition rows
Attrition$Parameter<-row.names(Attcor)

#Rename titles Attrition
names(Attrition)<-c("Correlation", "Parameter")

#Sort Attrition
SortAtt <- Attrition[order(-Attrition$Correlation),]

head(SortAtt,10)

```
Generate graphics

```{r echo=TRUE, comment=NA, results='asis'}

plot(Attrition~OverTime, data=df)
plot(Attrition~MaritalStatus, data=df)
plot(Attrition~DistanceFromHome, data=df)
plot(Attrition~JobRole, data=df)
plot(Attrition~Department, data=df)
plot(Attrition~NumCompaniesWorked, data=df)
plot(Attrition~Gender, data=df)
plot(Attrition~EducationField, data=df)
plot(Attrition~MonthlyRate, data=df)
```

Check with absolute values
```{r echo=TRUE, comment=NA, results='asis'}

Attrition$AbsAtt <- (Attrition$Correlation^2)^(1/2)
SortAbstAtt<- Attrition[order(-Attrition$AbsAtt),]
head(SortAbstAtt,10)
plot(Attrition~OverTime, data=df)
plot(Attrition~TotalWorkingYears, data=df)
plot(Attrition~JobRole, data=df)
plot(Attrition~ MaritalStatus, data=df)
plot(Attrition~YearsInCurrentRole, data=df)
plot(Attrition~MonthlyIncome, data=df)
plot(Attrition~Age, data=df)
plot(Attrition~YearsWithCurrManager, data=df)
plot(Attrition~StockOptionLevel, data=df)
```

check scatterplot
```{r echo=TRUE, comment=NA, results='asis'}
```